export const LOG_TABLE_SQL = `
  CREATE TABLE IF NOT EXISTS request_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    time TEXT NOT NULL,
    route TEXT NOT NULL,
    method TEXT NOT NULL,
    path TEXT NOT NULL,
    endpoint TEXT NOT NULL DEFAULT '',
    request_type TEXT NOT NULL DEFAULT 'http',
    reasoning_effort TEXT,
    request_summary TEXT,
    source_model TEXT,
    target_model TEXT,
    status INTEGER NOT NULL,
    duration_ms INTEGER NOT NULL,
    first_token_ms INTEGER,
    input_tokens INTEGER,
    output_tokens INTEGER,
    cached_input_tokens INTEGER,
    cached_output_tokens INTEGER,
    cache_read_input_tokens INTEGER,
    cache_creation_input_tokens INTEGER,
    reasoning_tokens INTEGER,
    additive_cached_input_tokens INTEGER NOT NULL DEFAULT 0,
    additive_cached_output_tokens INTEGER NOT NULL DEFAULT 0,
    total_tokens INTEGER,
    upstream_host TEXT NOT NULL,
    user_agent TEXT,
    request_id TEXT NOT NULL,
    error_summary TEXT
  );
  CREATE INDEX IF NOT EXISTS idx_request_logs_id ON request_logs(id DESC);
`;

export const RECENT_LOG_FIELDS = `
  time,
  route,
  method,
  path,
  endpoint,
  request_type,
  reasoning_effort,
  request_summary,
  source_model,
  target_model,
  status,
  duration_ms,
  first_token_ms,
  input_tokens,
  output_tokens,
  cached_input_tokens,
  cached_output_tokens,
  cache_read_input_tokens,
  cache_creation_input_tokens,
  reasoning_tokens,
  additive_cached_input_tokens,
  additive_cached_output_tokens,
  total_tokens,
  upstream_host,
  user_agent,
  request_id,
  error_summary
`;

export const MIGRATION_COLUMNS: Record<string, string> = {
  endpoint: "TEXT NOT NULL DEFAULT ''",
  request_type: "TEXT NOT NULL DEFAULT 'http'",
  reasoning_effort: "TEXT",
  request_summary: "TEXT",
  error_summary: "TEXT",
  first_token_ms: "INTEGER",
  input_tokens: "INTEGER",
  output_tokens: "INTEGER",
  cached_input_tokens: "INTEGER",
  cached_output_tokens: "INTEGER",
  cache_read_input_tokens: "INTEGER",
  cache_creation_input_tokens: "INTEGER",
  reasoning_tokens: "INTEGER",
  additive_cached_input_tokens: "INTEGER NOT NULL DEFAULT 0",
  additive_cached_output_tokens: "INTEGER NOT NULL DEFAULT 0",
  total_tokens: "INTEGER",
  user_agent: "TEXT"
};
