export const LOG_TABLE_SQL = `
  CREATE TABLE IF NOT EXISTS request_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    time TEXT NOT NULL,
    completed_at TEXT NOT NULL DEFAULT '',
    route TEXT NOT NULL,
    method TEXT NOT NULL,
    path TEXT NOT NULL,
    endpoint TEXT NOT NULL DEFAULT '',
    request_type TEXT NOT NULL DEFAULT 'http',
    reasoning_effort TEXT,
    request_summary TEXT,
    incoming_request_body TEXT,
    upstream_request_body TEXT,
    upstream_response_body TEXT,
    client_response_body TEXT,
    compact_response_normalized INTEGER NOT NULL DEFAULT 0,
    compact_response_normalize_reason TEXT,
    compact_response_synthetic_source TEXT,
    source_model TEXT,
    target_model TEXT,
    response_model TEXT,
    status INTEGER NOT NULL,
    duration_ms INTEGER NOT NULL,
    first_token_ms INTEGER,
    input_tokens INTEGER,
    output_tokens INTEGER,
    cached_input_tokens INTEGER,
    cached_output_tokens INTEGER,
    cache_read_input_tokens INTEGER,
    cache_creation_input_tokens INTEGER,
    reasoning_tokens INTEGER,
    additive_cached_input_tokens INTEGER NOT NULL DEFAULT 0,
    additive_cached_output_tokens INTEGER NOT NULL DEFAULT 0,
    total_tokens INTEGER,
    upstream_host TEXT NOT NULL,
    user_agent TEXT,
    request_id TEXT NOT NULL,
    error_summary TEXT
  );
  CREATE INDEX IF NOT EXISTS idx_request_logs_id ON request_logs(id DESC);
`;

export const RECENT_LOG_FIELDS = `
  time,
  completed_at,
  route,
  method,
  path,
  endpoint,
  request_type,
  reasoning_effort,
  request_summary,
  NULL AS incoming_request_body,
  NULL AS upstream_request_body,
  NULL AS upstream_response_body,
  NULL AS client_response_body,
  compact_response_normalized,
  compact_response_normalize_reason,
  compact_response_synthetic_source,
  source_model,
  target_model,
  response_model,
  status,
  duration_ms,
  first_token_ms,
  input_tokens,
  output_tokens,
  cached_input_tokens,
  cached_output_tokens,
  cache_read_input_tokens,
  cache_creation_input_tokens,
  reasoning_tokens,
  additive_cached_input_tokens,
  additive_cached_output_tokens,
  total_tokens,
  upstream_host,
  user_agent,
  request_id,
  error_summary
`;

export const MIGRATION_COLUMNS: Record<string, string> = {
  completed_at: "TEXT NOT NULL DEFAULT ''",
  endpoint: "TEXT NOT NULL DEFAULT ''",
  request_type: "TEXT NOT NULL DEFAULT 'http'",
  reasoning_effort: "TEXT",
  request_summary: "TEXT",
  incoming_request_body: "TEXT",
  upstream_request_body: "TEXT",
  upstream_response_body: "TEXT",
  client_response_body: "TEXT",
  compact_response_normalized: "INTEGER NOT NULL DEFAULT 0",
  compact_response_normalize_reason: "TEXT",
  compact_response_synthetic_source: "TEXT",
  response_model: "TEXT",
  error_summary: "TEXT",
  first_token_ms: "INTEGER",
  input_tokens: "INTEGER",
  output_tokens: "INTEGER",
  cached_input_tokens: "INTEGER",
  cached_output_tokens: "INTEGER",
  cache_read_input_tokens: "INTEGER",
  cache_creation_input_tokens: "INTEGER",
  reasoning_tokens: "INTEGER",
  additive_cached_input_tokens: "INTEGER NOT NULL DEFAULT 0",
  additive_cached_output_tokens: "INTEGER NOT NULL DEFAULT 0",
  total_tokens: "INTEGER",
  user_agent: "TEXT"
};
